# Generated by Django 5.1.6 on 2025-03-03 00:40

import django.db.models.deletion
import mods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=mods.models.homepage_logo_upload_path)),
                ('apresentacao_texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Seção da Página Inicial',
                'verbose_name_plural': 'Seções da Página Inicial',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=mods.models.mod_file_upload_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mods.models.mod_image_upload_path)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('icone', models.ImageField(upload_to=mods.models.rede_social_icone_upload_path)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ApresentacaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=mods.models.apresentacao_imagem_upload_path)),
                ('descricao', models.TextField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacao_imagens', to='mods.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=mods.models.noticia_imagem_upload_path)),
                ('video', models.URLField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='mods.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=mods.models.section_content_image_upload_path)),
                ('video', models.URLField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='mods.homepagesection')),
            ],
            options={
                'verbose_name': 'Conteúdo da Seção',
                'verbose_name_plural': 'Conteúdos das Seções',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SugestaoMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='mods.mod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mod')},
            },
        ),
    ]
