# Generated by Django 5.1.6 on 2025-03-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redesocial',
            name='icone_url',
        ),
        migrations.AddField(
            model_name='redesocial',
            name='icone',
            field=models.URLField(default='https://via.placeholder.com/100'),
            preserve_default=False,
        ),
    ]
