# Generated by Django 5.1.5 on 2025-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_sugestaomod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('icone', models.ImageField(upload_to='redes_sociais/')),
                ('link', models.URLField()),
            ],
        ),
    ]
