# Generated by Django 5.1.6 on 2025-02-28 01:49

import mods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_redesocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacaoimagem',
            name='imagem',
            field=models.ImageField(upload_to=mods.models.apresentacao_imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.homepage_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='mod',
            name='file',
            field=models.FileField(upload_to=mods.models.mod_file_upload_path),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.mod_image_upload_path),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.noticia_imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='icone',
            field=models.ImageField(upload_to=mods.models.rede_social_icone_upload_path),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.section_content_image_upload_path),
        ),
    ]
